Feature/new project setup
futureproofsoft/trainerr-frontend pull request #2
Opened 2023-11-28 23:19 UTC by pavle-doby

2023-11-28 23:32 UTC, todor996 requested changes

2023-11-28 23:32 UTC, todor996 commented on public/locales/en/translation.ts
> +const enRecourse: AppRecourse = {
Recourse -> Resource?

2023-11-28 23:32 UTC, todor996 commented on public/locales/sr/translation.ts
> +import { AppRecourse } from '../../../src/types/locales.type';
Same, everywhere

2023-11-28 23:32 UTC, todor996 commented on src/main.tsx
> +import App from "./App.tsx";
import ./App ? shouldn't require extension for import.

2023-11-28 23:32 UTC, todor996 commented on src/main.tsx
> +import { store } from "./store/index.store.ts";
same for ts/js/tsx/jsx

2023-11-28 23:32 UTC, todor996 commented on src/modules/home/Home.page.tsx
> +          onClick={() => setEnglish()}
() => setEnglish -> onClick={setEnglish}
no need to call func with empty parameters

2023-11-28 23:32 UTC, todor996 commented on src/modules/home/Home.page.tsx
> +          onChange={(event) => updateUserName(event.target.value)}
type for event

2023-11-28 23:34 UTC, todor996 commented on src/modules/settings/Settings.page.tsx
> +import "Settings.style.css";
do we need css for each page/component? i think not if using tailwind, its enough to import just tailwind globally

2023-11-28 23:41 UTC, pavle-doby commented on src/modules/home/Home.page.tsx
> +          onChange={(event) => updateUserName(event.target.value)}
Maybe it is going to be an overkill to add that type in JSX since it can become messy and unreadable...
Autocomplete works without explicitly defining it. 
But I like enthusiasm about types. 😃

2023-11-28 23:43 UTC, pavle-doby commented on src/modules/settings/Settings.page.tsx
> +import "Settings.style.css";
Tailwind is enabled globally... Here I just added it as an example of how we can add custom CSS if we need it... 
But the general idea would be to avoid custom CSS and use `tailwind` + `daisyUI` as much as possible.

2023-12-24 00:03 UTC, todor996 approved these changes

2023-12-24 00:03 UTC, merged