Remove unused package & audit fix with npm
futureproofsoft/trainerr-frontend pull request #9
Opened 2024-01-20 20:00 UTC by pavle-doby

2024-01-21 23:06 UTC, todor996 requested changes

2024-01-21 23:06 UTC, todor996 commented on src/modules/auth/Auth.router.tsx
> +      path: 'sing-up',
typo, sign-up

2024-01-21 23:06 UTC, todor996 commented on src/modules/auth/components/LogIn/LogInSection.tsx
> +            You don't have an account?{' '}
same, /sign-up

2024-01-21 23:06 UTC, todor996 commented on src/modules/clients/trainer/Clients.router.tsx
> +import { RouteObject } from 'react-router-dom';
mozda globalno da napravis Trainer router, da ne pises svuda trainer/ruta, nego tipa
TrainerRouter koji ce da ima subroutere

2024-01-23 23:45 UTC, pavle-doby commented
In this PR there is a lot of experimenting... However, the `trainer-pov` module is the closest to a final structure/organization of files and code. Maybe a few tweaks in the code here and there and maybe we will remove the "pov" suffix (`.tpov`).

So, take a look, think about it and give me your thoughts. 😊

2024-02-01 00:05 UTC, merged